### ISSUE TITLE
change ruleset-id identifier to alias_name production

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcrvalidator#11]
Right now ruleset-id is a uri. But this will lead to endless issues about the uri being resolvable, etc... It is merely intended to be an idenfitier to be used in an implementation catalog. I think we should change this to alias_name because that is closer to what its intended purpose is suppose to be.

**Comment by codalogic** [comment]
I agree.  I think it should be possible to set it to a uri, but it should also be possible to set it to the "com.codalogic.foo.bar" form, plus URNs (if they're not a subset of URIs!).

**Comment by anewton1998** [comment]
Given that namespace_alias doesn't match some URIs (or URNs) or "com.codalogic.foo.bar", we'd need a new grammar production. Something like:
    rule(:ruleset_id) { match('[a-zA-Z]').repeat(1) >> match('[\S]').repeat(1) }

Does this sound good?

**Comment by codalogic** [comment]
Works for me, but to match other name style rules I'd simplify it to:

rule(:ruleset_id) { match('[a-zA-Z]') >> match('[\S]').repeat }

**Comment by anewton1998** [comment]
Yeah, that's better

**Comment by anewton1998** [comment]
done
