### ISSUE TITLE
Support for jCard - or not!

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#12]
I had a look at jCard and I do wonder how much effort should be put into supporting such atrocities! (What do they have against using objects!)  Flaky edge cases to meet flaky scenarios is likely to lead to flaky tools which in the end serves the community less well than simpler, hardened tools.

xCard has done a much better job of turning vCard into XML, and I wonder if that's in part to do with it using Relax NG which steers you into coming up with sensible grammars.

Also, if we go back to the original vCard, the spec is more like:

jCard [ * contentline ]
contentline [ name, params, value-type, value-value ]
name : string
params { ? blah, ? blah }
value-type : ( :"fn", :"n" etc )
value-value ( ; lots of messy stiff ;; )

Maybe that's good enough for this case?

**Comment by anewton1998** [comment]
Not that I want to write a jCard rule set, but the ability to support sub arrays and objects in this manner is not hard at all. In fact, in this code base its a give me.

The extra coding is on verifying that no rule matches an item twice, which I can't imagine is a lot of work.

**Comment by codalogic** [comment]
I'll have to have a look at the code.  It sounds horrendous to me!  Especially if there are deep nested hierarchies that each in turn need unordered matching.  Sounds like the potential for lots of roll-back, and scope for denial of service attacks.  But maybe we have to rely on the language designer being sensible.  (But can we rely on that?!!!)
