### ISSUE TITLE
per rule directives

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcrvalidator#13]
To help clarify the conversation over the other issues, the idea of a directive specified on a rule is that we use the `@(blah)` syntax.

The general form is
~~~
rule_name @(directive param,param) rule_def
~~~

And for multiple directives it would be
~~~
rule_name @(dir1 p1, p2) @(d2) rule_def
~~~

At present we have the following directives proposed:
* unordered - for arrays
* reject - for all rule types
* possibly array-group, object-group, value-group, member-group for constraining groups
  * this could be @(constrain to_arrays, to_objects)

So we could potentially have this example which would fail any array with the string "OOPS!" in it
~~~
bad_array @(reject) @(unordered) [ "OOPS!", * :any ]
~~~

**Comment by codalogic** [comment]
Looks good.  I would allow the parameters in the directives to be more free-form, so @(dir2 p1 p2) would be OK, in addition to @(dir1 p1, p2).  This allows for things like @(import net.arin.email as email) to be more natural.

I would also put the directives within the object / array / group brackets, so you have:

    bad_array [ @(reject) @(unordered) "OOPS!", *:any ]

That way you can use the same syntax when arrays etc are nested without having ambiguity as to which one it refers to, e.g.:

    my_rule [ *:int, [ @(reject) @(unordered) "OOPS!", *:any ] ]

**Comment by anewton1998** [comment]
Yes, the directive parameter should be free form. Sine we'll be describing the grammar for each anyway, there's no need to lock them down.

Let's explore the prefix and postfix syntax proposals.

Prefix:
~~~
bad_pi @(reject) : 3.17
bad_pie @(reject) "pie" pi_value
bad_pies @(reject) [ * pi_value ]
pi_batch [ * pi_value ]
bad_baker @(reject) [ * pi_tins, * pi_value ]
bad_batch @(reject) [ * pi_batch ]
pi_contest { * contestants, * "good_pies" pi_batch, "bad_pies" bad_batch ]
pi_contest { * contestants, * "good_pies" pi_batch, (@reject)  pi_batch }
~~~

Postfix:
~~~
bad_pi : (@reject) 3.17
bad_pie "pie" (@reject) pi_value ;am I rejecting pi_value or a member named "pie" with a value or pi_value?
bad_pies  [ (@reject) * pi_value ]
pi_batch [ * pi_value ]
bad_baker [ (@reject) * pi_tins, * pi_value ] ;am I rejecting the entire array or just pi_tins?
bad_batch [ @(reject) * pi_batch ]
pi_contest { * contestants, * "good_pies" pi_batch, "bad_pies" bad_batch ]
pi_contest { * contestants, * "good_pies" pi_batch,  pi_batch @(reject) } ;is this even legal syntax?
~~~

By putting the directive inside the syntax elements that defines the rule, there are some corner cases:
* for member rules it goes after the regex or string because putting it inside of those would be odd. So it goes after but then can lead the reader to think you are rejecting the value and not the member
* for array and object rules it comes after [ and { and the reader could assume it only applies to the first item or member instead of the entire array or object
* it cannot be used when referencing a rule by a name, atleast I think.

**Comment by codalogic** [comment]
Now I think about it, prefix should be easier to fit in the grammar.  It may just be a single addition, rather than splashed all over the place.  Plus instead of my example of:

    my_rule [ *:int, [ @(reject) @(unordered) "OOPS!", *:any ] ]

you could do:

    my_rule [ *:int, @(reject) @(unordered) [ "OOPS!", *:any ] ]

The import example could be written something like:

   my_rule [ *int, @(import net.arin.tel as tel) { "tel" tel.phone } ]

Or, maybe:

   my_rule [ *int, @(using net.arin.tel as tel) { "tel" tel.phone } ]

**Comment by anewton1998** [comment]
A first pass of the grammar for rule directives is checked in. @codalogic please feel free to submit a pull request with changes to it if you see an opportunity to make the parslet rules better.

**Comment by codalogic** [comment]
One thing that the grammar allows at the moment is:

    my_rule (@directive1) "rule1" (@directive2) [:int]

Is there an difference in meaning between a directive before or after a member name?

I would also be inclined not to bake the directives directly in the ABNF, but just have a generic directive grammar ( something like: str('@(') >> name.as(:directive_name) >> ( spaces >> match('[^)]').as(:directive_parameters) ).maybe >> str(')') ) and enumerate the valid ones and their formats in prose in another part of the document.

**Comment by anewton1998** [comment]
I was attempting to make the parser invalidate directives that were not appropriate, but that is looking difficult. It is probably best to have that happen at a layer that is not the parser.

However, I thought it would be good to define the syntax for each of the directives. Are you suggesting we leave them to be free-form and/or implementation dependent?

**Comment by anewton1998** [comment]
regarding
~~~
my_rule (@directive1) "rule1" (@directive2) [:int]
~~~

Yes, that is valid. That is three rules: a member containing an array rule containing a value rule. directive1 applies to the member rule and directive2 applies to the array rule. That example could go further:

~~~
my_rule (@directive1) "rule1" (@directive2) [ (@directive3) :int]
~~~

However, I really doubt we'll ever get things like that in real life.

**Comment by anewton1998** [comment]
I just pushed a new branch rule_directives_take2. See if you like that.

**Comment by codalogic** [comment]
How about something along the lines of below?  I've included the ones we know about, but allowed others to be defined.  I also couldn't resist doing a bit of DRY-ing!

    rule(:reject_directive) { str('reject').as(:reject_directive) }
    rule(:unordered_directive) { str('unordered').as(:unordered_directive) }
    rule(:root_directive) { str('root').as(:root_directive) }
    rule(:TBD_directive) { name.as(:directive_name) >> ( spaces >> match('[^)]').as(:directive_parameters) ).maybe )
    rule(:rule_directive_set) { reject_directive | unordered_directive | root_directive | TBD_directive }
    rule(:rule_directives) { spcCmnt? >> (str('@(') >> rule_directive_set >> str(')') >> spcCmnt? ).repeat }

**Comment by codalogic** [comment]
I've gone a bit strict on, say @(root) must appear as @(root), but not @( root), @(root ) or @( root ).  Personally I like that style, but is that imposing a style when it shouldn't?

**Comment by anewton1998** [comment]
I agree that I like `@(root)` better than `@( root )` but I also recognize people have different style opinions. So if it doesn't take too much effort, I favor not constraining them.

I've incorporated your rules into the branch and will merge it back to master.

**Comment by codalogic** [comment]
Seems sensible.

I'm wondering if they should be called something other than 'directives' to avoid possible confusion with the top-level directives.  'Annotations' maybe?

**Comment by anewton1998** [comment]
That had crossed my mind. I'm not gonna fall on my sword over it, but I think a distinction between a rule set directive and rule directive can be easily described. But I can be swayed. Do you feel it will be confusing the way it is now?

**Comment by codalogic** [comment]
I would change it.  Ambiguity is a killer.  It'd be a quick fix now that you'd probably save in confusion for, hopefully, the years down the line.

**Comment by anewton1998** [comment]
You've convinced me. I'll change it to annotations.

**Comment by anewton1998** [comment]
This is done and now in master
