### ISSUE TITLE
closing out syntax changes

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcrvalidator#24]
While there are some implementation issues (which I will open up soon so I can keep track of them) left to be done, I think all syntax changes have been made.

@codalogic unless you have some other proposals, I think we are finished with changes to the syntax if you want to start on the ABNF.

**Comment by codalogic** [comment]
OK, I'll get on it.  (I'm on a train much of today so the timing is good!)  If I come across any issues I'll let you know.
