### ISSUE TITLE
Annotations and future value properties

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#39]
Just to check that there are enough extensibility options in the grammar....

imagine in future it's desired to add an explicit constraint on string length, or maybe able to specify that an integer must satisfy a constraint, do you envision using syntax such as the following:

    short_string (@length 0..10) : string
    odd_int (@satisfies $ % 2 == 1) : integer

Or do you think some other option, possibly non-attribute based, would be used?

**Comment by anewton1998** [comment]
That's interesting, but ultimately we need to realize when we are getting into programming language territory. I was originally thinking that locally a programmer could pass callback functions into the JCR processor such that the callback is called when `odd_int` is evaluated.

Setting this up in the JCR is interesting. Perhaps another way to do this:

~~~
odd_int @(check-code my_code) : integer

# code my_code(ruby)
# code my_code: def my_def data
# code my_code:   return data % 2
# code my_code: end
~~~

However, I don't think we have to work this out now... though I might include a section in the appendix discussing it.

**Comment by anewton1998** [comment]
Just thinking about this a little more, a better syntax might be:

~~~
odd_int @(check-code my_code) : integer

# code my_code(ruby-2.0)
## def my_def data
##   return data % 2
## end
~~~

**Comment by codalogic** [comment]
JCRCC targets this (although it needs a better write up still)
