### ISSUE TITLE
ABNF case sensitivity

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#40]
Recalling that if you define a string to be matched in ABNF such as "jcr-version", this is invokes case-insensitive matching and so the defined grammar will also allow "JCR-version", "jCr-VeRsIoN" and so on.  Is this what is wanted or should case specific matching be defined using the %x45.65.34 etc style of defining names?

**Comment by anewton1998** [comment]
Interesting. I had not realized this. But making it case sensitive would be make the ABNF unreadable.

So I think we leave it case insensitive and get Parslet to match case insensitive, which can be done based on this: http://kschiess.github.io/parslet/tricks.html#toc-matching-strings-case-insensitive

That's my opinion. But does this make other implementations difficult?

**Comment by codalogic** [comment]
The way case sensitivity is often done is something like:

jcr-version_d = jcr-version-kw 1*WSP major-version "." minor-version
jcr-version-kw = %x6A.63.72.2D ... ; "jcr-version"

I can get the python to do the conversion if necessary.  So I think the important thing is to do what's right for JCR, not what works conveniently for ABNF.  If it's more problematic for Ruby and possibly other languanges, then being case sensitive seems the better option to me.

**Comment by anewton1998** [comment]
Well, this is really a tooling issue of which I cannot profess to have enough experience.

Since there aren't that many keywords in JCR, perhaps going with case sensitive is the best approach for now.

**Comment by codalogic** [comment]
Thinking some more, since the JSON RFC defines a case-sensitive syntax, for example, defining syntax as below, it makes sense that JCR is also.  That will hopefully be the least surprising for people.

      value = false / null / true / object / array / number / string
      false = %x66.61.6c.73.65   ; false
      null  = %x6e.75.6c.6c      ; null
      true  = %x74.72.75.65      ; true

**Comment by anewton1998** [comment]
I think that is a good reason.

**Comment by codalogic** [comment]
Closed for now
