### ISSUE TITLE
value-rule to primitive-rule?

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#44]
In JSON a 'value' includes objects and arrays, but in JCR it excludes them.  It seems a good idea to align the definitions, but that leaves what to call what is now 'value-rule' and friends.  RFC 7159 (JSON) uses 'primitive' (once only in the text) to describe the non-object / array types.  json.org doesn't reference it, nor does ECMA 404 (they don't distinguish between the types of values).  In an effort to align to something, 'primitive-rule' seems as good as any.

**Comment by anewton1998** [comment]
I agree. primitive-rule sounds good. How do we want to balance this with value rules that accept arrays and objects (e.g. `:[ ... ]`)?

**Comment by codalogic** [comment]
I'm thinking of changing the existing `value-rule` to `primitive-rule` (plus its children), and then doing:

    type-rule = value-rule / target-rule-name
    value-rule = primitive-rule / object-rule / array-rule  ; new

I'll create a branch (with all the tests updated) so you can see if it looks OK.  (I think the tests will be the more time consuming part of the change.)

**Comment by anewton1998** [comment]
Sounds good to me.

**Comment by codalogic** [comment]
All done!
