### ISSUE TITLE
Allow colon before object / array def

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#45]
Your new draft introduction showing a JSON message is actually a JCR ruleset, and the examples on the web page (http://codalogic.github.io/jcr/) highlighted that it might make sense to allow colons to precede object and array definitions so it is more JSON-like.  (e.g. allow: rule : {} ).  That makes an introduction to JCR from a JSON example even more straight forward than it is now.  ABNF-wise, I think we can even make the colon optional if desired.

I suppose the downside is that it becomes difficult to tell apart a JSON message and a JCR definition!

But the upside to that downside is that it would be much easier to craft JCR test cases from example JSON messages.

**Comment by anewton1998** [comment]
I noticed this as well, and I agree. we should allow the colon before array and object rules.

**Comment by codalogic** [comment]
OK.  I'll make it optional for the time being.  That'll allow:

    rule : [ : integer, [ a, b ], { c, d } ]

which, for the time being(!), seems more natural.

**Comment by codalogic** [comment]
Just realised that a colon before an object rule could be confused with a uri-template that begins with a { character.  We could change the uri-template { char to a < (or maybe use ${ and } - < does seem to cause problems).  Or we could wrap uri-templates in <> brackets (or do similar) or prefix them by something (e.g. $).  The latter approaches have the advantage that currently the uri-template syntax is quite permissive and will clash with any primitive type that might be declared in future versions causing an old implementation to accept it as a uri-template when it would be better to report an error.

**Comment by codalogic** [comment]
Just realised that RFC6570 defines the syntax for uri-templates so we can't change that.  So maybe preceding a uri-template with something like a $ is the best we can do.  Not pretty, but I'd rather do that than prevent objects starting with a colon.

**Comment by anewton1998** [comment]
Given that URI syntax is a disaster, I'm fine with prefixing $. Actually, I'm fine with prefixing u$, where u means URI template. This is some future proofing in case we ever add something else that has conflicts. But I'll let you decide if we want to go that far. I'm definitely good with your proposed solution of $.

**Comment by codalogic** [comment]
I'm thinking of merging the uri and uri-template rules so we have:

    rule(:uri_type)       { str('uri').as(:uri) >> ( spaces >> str('as') >> spaces >> uri_template).maybe }
        #! uri_type = uri-kw [ spaces as_kw uri_template ]
        #> uri-kw = "uri"

giving an example rule of:

    rule : uri as http://{whatever}

A bit more verbose than the rest of the syntax.  And it does break the pattern of only having one non-space containing token sequence for a primitive rule.  If you'd rather not do that we could do something like the following:

    rule : uri$http://{whatever}
    rule : uri>http://{whatever}

**Comment by codalogic** [comment]
For the time being I've pushed a variant that does:

    rule : uri..http://{etc}

on the basis that .. is used to represent a range in other data types, and a uri-template is a range of uris!  Possibly an odd choice, but it has some rationale over choosing some other random character!

**Comment by anewton1998** [comment]
This works for me. The pull request is merged.
