### ISSUE TITLE
Incorporating parser.rb with ABNF comments into master

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#46]
How do you feel about moving my version of lib/jcr/parser.rb into your master branch?  It does have a extraneous stuff for a product that is just a pure validator, but will help me keep the Parslet verification code and the ABNF in sync.

If you're up for it, I'll create a pull request off your current master, and include my abnf creation Python script as well.  I'll double check it passes all the tests before submitting it!

**Comment by codalogic** [comment]
Should have said, you can see my copy at:

https://github.com/codalogic/jcrvalidator/blob/abnf_prep/lib/jcr/parser.rb

**Comment by anewton1998** [comment]
Yeah, that sounds good to me.
