### ISSUE TITLE
LL(1) parser friendliness

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#51]
Over the weekend I was looking into various types of parsing techniques.  Turns out most of the parsers I've implemented are recursive descent with single token / character look-ahead (LL(1)).

The way we currently have annotations (and to a lesser extent colons) means that the JCR ABNF is not LL(1) compatible.  It may be necessary to parse any annotations and back-track up to four times.  Parslet does this very well, but the C++ Boost::Spirit library (which is more XML SAX like in that it fires off events as it parses input) used naively would potentially quadruple up the annotations identified on a rule.  Not only is this less efficient it also requires more work from the developer.  I figure the easier the grammar is to implement, the more implementations there will be, and the more success JCR will have.

Thus this was troubling me, so I looked to see if the grammar could be de-conflicted.  Alas it can be, but at the loss of clarity in the ABNF, and also the potential for introducing errors.

So I propose we leave the grammar as it is and accept that it is not LL(1) friendly. If anyone brings it up we can say we know, but we decided it's not that big-a-deal.  Although the grammar allows annotations, they are a typically rare (so the inefficiency won't occur) and typical scenarios where JCR is used are not likely to be performance critical.

I thought I'd capture this suggestion here to act as a record of the rationale for not changing the grammar to address this.  Naturally if you disagree with the approach let me know.  But if you're happy to go with it then feel free to close it thus 'logging' it as a resolved issue.

**Comment by anewton1998** [comment]
I'm happy to go forward with it, but shouldn't this be on the JCR draft project. We could definitely put some text in the draft discussing our decision.

**Comment by anewton1998** [comment]
Oh, and thanks for taking the time to look at it.

**Comment by codalogic** [comment]
I'll copy it to the JCR project with a note to put something in the draft, and close it here
