### ISSUE TITLE
Generalising type-choice

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#53]
In `member_rule` we have `(type_rule | type_choice)`.  In `primitive_rule` we have `primimitive_choice | primimitive_def` (just realised I need to fix some spelling there!).

But it seems that it should be possible to have a choice of types wherever a type can appear.  That suggest raising the choice of types into something like `type_rule`.

However, `rule_def` (which uses `type_rule`) correctly allows for groups which are denoted by round brackets.  Hence a type_choice needs some way of distinguishing it so a parser doesn't get confused.  The logical solution is to require a colon before a `type_choice`.  So you would have:

    rule "member" : ( :integer | :string )

(which is how a `primitive_choice` looks at the moment), or, moving into new territory:

    rule "member" : ( : null | { "stuff" stuff } )

This would have looked a bit odd before we allowed colons to appear before object and array types, but now it is allowed it looks quite reasonable.

I've worked through the impact of this at https://github.com/codalogic/jcrvalidator/tree/promote-type-choice , but the headline change is using:

    rule(:type_rule)   { value_rule | target_rule_name | ( str(":") >> spcCmnt? >> type_choice ) }

and removing type_choice and primitive_choice usages from other places.  I also fixed up most of the tests, which mainly involved adding colons to constructs such as the following as they would no longer be valid:

    rule "member" ( "empty" | { "stuff" stuff } )

A few tests still fail, which it would be worth you looking at to decide if you can accept them.

So what do you think?  To me the change makes things look more orthogonal, which usually makes things simpler and more powerful at the same time.

**Comment by anewton1998** [comment]
I don't quite understand all the details, but from hi-level I agree with this.
Let me pull the code and work through the tests.
There is other code cleanup I need to do as well, but I'd like to get to this first.

**Comment by codalogic** [comment]
It does make my head hurt when thinking about it, so I'd welcome you taking your time going over it.

I pushed another version with some editorial renamings, but after seeing the changes implemented for a while changed my mind and reverted them!

**Comment by codalogic** [comment]
Obsolete. Latest code addresses this, but in a slightly different way
