### ISSUE TITLE
Audit of ABNF

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#54]
I've done a review / audit of the manually converted ABNF I did.  There's a couple of little things that showed up.  The initial changes are in the branch:

https://github.com/codalogic/jcrvalidator/tree/abnf-audit

This is relative to your arineng/master, and doesn't include the 'promote-type-choice' changes included.

I've then merged these changes into the 'promote-type-choice' branch, made a couple more changes and ended up with:

https://github.com/codalogic/jcrvalidator/tree/promote-type-choice

**Comment by anewton1998** [comment]
This is done. As for the 3 passing tests:
1) the first issue was that the parser was no longer producing a token in the result hash that allowed check_groups to determine a group_rule in a value_rule. I put in a simple token for the type_choice_signifier and a check for that.
2) The other two tests were things that parser was able to catch before... objects and arrays deeply embedded in value rules. The fact that the parser could ever do this was amazing. But it can't any more. However, the logic to catch these errors was already in group_check so I just moved the tests over.
