### ISSUE TITLE
Possible bug in validator

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#59]
I may be doing things wrong, but when I use the command-line JCR validator program with JCR as follows:

    mrule "mname" : integer

and JSON as:

    [ "mname", 12 ]

and specifying the root rule to be 'mrule', I get a 'Success!'

That seems an odd result to me.  Have I misunderstood or does something need to be fixed?

**Comment by codalogic** [comment]
Another possible bug...

I modified the following test from evaluate_group_rules_spec.rb, line 60 ish:

        tree = JCR.parse( 'trule : @(reject) ( :ip4 | :integer )' )
        mapping = JCR.map_rule_names( tree )
        JCR.check_rule_target_names( tree, mapping )
        e = JCR.evaluate_rule( tree[0], tree[0], "a string constant", JCR::EvalConditions.new( mapping, nil ) )
        expect( e.success ).to be_truthy

To avoid having a JSON message consisting of only a value (which the Ruby JSON parser doesn't accept) to yield the test:

     ## should pass a group with an ip4 or an integer with reject
    JCR: Pass
        [ trule ] trule : @(reject) ( :ip4 | :integer )
    JSON: Pass
         [ "a string constant" ]

But in fact the JSON test _fails_.  To be honest I'm not sure that's an unreasonable result, but may need a little thought.  This message here is mainly to log it for future consideration.

**Comment by codalogic** [comment]
I think `Context.self.ingest_ruleset(...)` needs to call `JCR.check_groups(...)`, otherwise tests like the following give the incorrect result:

    #-- Line: 60
    #--     tree = JCR.parse( 'grule ( :ip4 , :ip6 ) ;; mrule "thing"  :integer | grule ) ' )
    #--     mapping = JCR.map_rule_names( tree )
    #--     JCR.check_rule_target_names( tree, mapping )
    #--     expect{ JCR.check_groups( tree, mapping ) }.to raise_error RuntimeError
    ## should error with member with group of value OR rulename with AND
    JCRFull: Fail
        mrule "thing"  :integer | grule ) ;; grule ( :ip4 , :ip6 )

**Comment by codalogic** [comment]
The major and minor version numbers in the jcr-version directive should use p_integer rather than integer.  i.e. instead of:

    rule(:jcr_version_d) { (str('jcr-version') >> spaces >> integer.as(:major_version) >> str('.') >> integer.as(:minor_version)).as(:jcr_version_d) }
        #! jcr_version_d = jcr-version-kw spaces major_version "." minor_version
        #> jcr-version-kw = "jcr-version"
        #! major_version = integer
        #! minor_version = integer

use:

    rule(:jcr_version_d) { (str('jcr-version') >> spaces >> p_integer.as(:major_version) >> str('.') >> p_integer.as(:minor_version)).as(:jcr_version_d) }
        #! jcr_version_d = jcr-version-kw spaces major_version "." minor_version
        #> jcr-version-kw = "jcr-version"
        #! major_version = p_integer
        #! minor_version = p_integer

**Comment by codalogic** [comment]
Currently the grammar allows newlines in the middle of directives.  e.g.:

    rule(:jcr_version_d) { (str('jcr-version') >> spaces >> p_integer.as(:major_version) >> str('.') >> p_integer.as(:minor_version)).as(:jcr_version_d) }
        #! jcr_version_d = jcr-version-kw spaces major_version "." minor_version

allows (if we go back to the rule(:directive) rule):

    # 
    jcr-version
    0.5

I don't think this is the intent.  We could replace the 'spaces' rules with '1*WSP' etc to keep it on one line.

**Comment by codalogic** [comment]
ABNF for 'directive_parameters' needs to be changed from:

            #! directive_parameters = not_eol

to:

            #! directive_parameters = *not_eol

**Comment by anewton1998** [comment]
Indeed, there are multiple bugs here:

```
$ echo '[ "mname", 12 ]' | jcr -R 'mrule "mname" : integer' -s mrule -v
Success!
```

That's wrong.

And 
```
$ echo '[ "mname", 12 ]' | jcr -R 'mrule "mname" : integer'
/Library/Ruby/Gems/2.0.0/gems/jcrvalidator-0.5.1/lib/jcr/jcr.rb:119:in `evaluate_ruleset': No root rule defined. Specify a root rule name (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/jcrvalidator-0.5.1/lib/jcr/jcr.rb:56:in `evaluate'
	from /Library/Ruby/Gems/2.0.0/gems/jcrvalidator-0.5.1/lib/jcr/jcr.rb:231:in `main'
	from /Library/Ruby/Gems/2.0.0/gems/jcrvalidator-0.5.1/bin/jcr:25:in `<top (required)>'
	from /usr/bin/jcr:23:in `load'
	from /usr/bin/jcr:23:in `<main>'
```
but I shouldn't have to specify a root.

Let me look into this.

**Comment by codalogic** [comment]
Grammar should allow whitespace at the end of directives just to save the sanity of coders.  i.e. instead of:

    rule(:directive) { ( str('#') >> spaces? >> directive_def >> match('[\r\n]') ).as(:directive) }
        #! directive = "#" spaces? directive_def eol

do:

    rule(:directive) { ( str('#') >> spaces? >> directive_def >> spaces? >> match('[\r\n]') ).as(:directive) }
        #! directive = "#" spaces? directive_def *WSP eol

**Comment by codalogic** [comment]
The following also needs changing from:

        #! uri_template = 1*ALPHA ":" not-space

to:

        #! uri_template = 1*ALPHA ":" 1*not-space

**Comment by anewton1998** [comment]
Just realized that this is in fact not a bug:
```
$ echo '[ "mname", 12 ]' | jcr -R 'mrule "mname" : integer'
```

**Comment by anewton1998** [comment]
Fixed the issue with member rules being used as a root rule:
```
$ echo '[ "mname", 12 ]' | jcr -R 'mrule "mname" : integer' -S mrule
```

The fix is to not allow this, since a member rule as a root doesn't make sense.

**Comment by codalogic** [comment]
Agreed, preventing member rules being group rules make sense.  We could also change the parser accordingly, e.g. from:

    rule(:root_rule) { value_rule | member_rule | group_rule } # N.B. Not target_rule_name
        #! root_rule = value_rule / member_rule / group_rule

to:

    rule(:root_rule) { value_rule | group_rule } # N.B. Not target_rule_name
        #! root_rule = value_rule /  group_rule

My plan is to finish off the parsing side of my C++ code, and then fixup all the little glitches I've noted above in one go.  Hope that's OK.

**Comment by anewton1998** [comment]
Ok by me!

**Comment by anewton1998** [comment]
Pete, I've taken care of many of these, but...

1. I don't understand this issue: https://github.com/arineng/jcrvalidator/issues/59#issuecomment-171949356
2. I've taken care of the check_rules inside ingest_rules as you mentioned. good catch.
3. I've taken care of the p_integer for JCR versioning.
4. I don't understand the newline/whitespace issue in the directive (https://github.com/arineng/jcrvalidator/issues/59#issuecomment-174010245) so I didn't ouch it.
5. I change the directive_parameters ABNF as you suggested
6. I updated the ABNF for whitespace after directives, as you suggested. However, Parslet already allowed it and had problems with the change, so I only applied it to the ABNF. A test for parslet has been added.
7. Change the uri_template ABNF
8. And I changed the root_rule to remove member_rule as you suggested.

**Comment by codalogic** [comment]
This looks great.  I've updated the various issues above with a little tag to say whether they've been handled, and broken out those that need more clarification into separate issues.

I still need to look at https://github.com/arineng/jcrvalidator/issues/59#issuecomment-171949356 again.

**Comment by codalogic** [comment]
Hopefully this is all taken care of
