### ISSUE TITLE
Ambiguity between group and type-choice within arrays and groups

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#72]
I'll fill this out a bit more when I'm a bit more refreshed!!!  But in short, when I have:

    $r = [ ( integer | string ) ]

and because we have the ABNF rule:

    array-item-types = type-rule / array-group

wanting to avoid too much backtracking, my code currently assumes that the above is a type-choice and not an array-group (similar for group-item-types).  We could flip things around so array-group has precedence, i.e.:

    array-item-types = array-group / type-rule

The top form would then always lead to an array-group.  Maybe OK for arrays, but possibly not so good for groups.

If we want to allow for explicit specifying of a type-choice, we could support:

    $r = [ ( integer | string ) ]     ; An array-group
    $r2 = [ : ( integer | string ) ] ; An explicit-type-choice

by doing:

    array-item-types = array-group / type-rule / explicit-type-choice
    explicit-type-choice = ":" *sp-cmt type-choice

**Comment by anewton1998** [comment]
Isn't the end result the same regardless?

**Comment by codalogic** [comment]
A type-choice only allows things like:

    $r = [ ( integer | string ) ]

whereas an array-grouping allows:

    $ag = [ ( integer@+ , string@+ ) | ipv6 @+ ]

For most cases an array-grouping is a superset of a type-choice, which is why I think we should give it precedence by swapping the order of the rules around.

Including the explicit-type-choice option gives us some protection if we later find it's useful to be able to distinguish between an array-grouping and a type-choice.

**Comment by anewton1998** [comment]
Ok, now I see your point. Yes, I believe array-group should have higher precedence. And I agree with your other point. If we put in explicit type-choice then we are future proofing.  Good catch!

**Comment by codalogic** [comment]
Cool. I'll put together a patch
