### ISSUE TITLE
Rules for parsing URI templates

### ISSUE THREAD

**Issue by pkyzivat** [arineng/jcrvalidator#75]
I just started using JCR. I have a desire to specify URIs with specific schemes (especially sip).

I thought that "uri:..sip" fit the bill. But to use that form I need to supply a URI template, and I can't figure out how to write a URI template that matches all valid sip URIs. 

RFC6570 is defined in terms of using templates to *generate* URIs, not to parse them. It isn't at all evident to me how (or if) it can be inverted in order to generate a parser. Can you explain, or give a reference, for how that is expected to be done?

In absence of a way to write a template that matches anything, I wish for one of the following revisions to the JCR syntax:

- uri..scheme  (no template, implying match anything)

- uri..scheme:/RE/

Of course I can just use a RE for this ( /^sip:.*$/ ). But that doesn't leap out and say that it is a URI the way that "uri.." does.

**Comment by anewton1998** [comment]
so my initial thought is that `uri..sip:{stuff}` should work, but:

```
→  bin/jcr -v -R '[ uri..sip:{stuff} ]' -J '[ "sip:1-999-123-4567@voip-provider.example.net" ]'
"Ruleset Parse Tree"
[{:array_rule=>{:primitive_rule=>{:uri_template=>"sip:{stuff}"@7}}}]
"Ruleset Map"
"Evaluating Root:"
" [ URI template sip:{stuff} ]"
[ 1:[1, 8]@7 ] Evaluating array rule starting at '"sip:{stuff}"@7' ( line 1 column 8 ) against data: ["sip:1-999-123-4567@voip-provider.example.net"]
[ 1:[1, 8]@7 ] array:  [ URI template sip:{stuff} ] data: ["sip:1-999-123-4567@voip-provider.example.net"]
[ 1:[1, 8]@7 ] rule repetition min = 1 max = 1 repetition step =
[ 2:[1, 8]@7 ] Evaluating value rule starting at '"sip:{stuff}"@7' ( line 1 column 8 )
[ 2:[1, 8]@7 ] value: URI template sip:{stuff} data: "sip:1-999-123-4567@voip-provider.example.net"
[ 2:[1, 8]@7 ] Value evaluation failed: expected sip:{stuff} but got sip:1-999-123-4567@voip-provider.example.net for  rule at '"sip:{stuff}"@7' ( line 1 column 8 ) [ {:uri_template=>"sip:{stuff}"@7} ] from rule at '"sip:{stuff}"@7' ( line 1 column 8 )
[ 1:[1, 8]@7 ] Array evaluation failed: More itmes in array than specified for  rule at '"sip:{stuff}"@7' ( line 1 column 8 ) [ [{:primitive_rule=>{:uri_template=>"sip:{stuff}"@7}}] ] from rule at '"sip:{stuff}"@7' ( line 1 column 8 )
Failure: More itmes in array than specified for  rule at '"sip:{stuff}"@7' ( line 1 column 8 ) [ [{:primitive_rule=>{:uri_template=>"sip:{stuff}"@7}}] ] from rule at '"sip:{stuff}"@7' ( line 1 column 8 )
```

I suspect this is a bug. I will look into it.

**Comment by anewton1998** [comment]
It looks like the Addressable URI template library we use has some issues:

```
irb(main):001:0> require 'addressable'
=> true
irb(main):002:0> template = Addressable::Template.new( "sip:1-999-123-4567@voip-provider.example.net" )
=> #<Addressable::Template:0x3fc6b4cceab0 PATTERN:sip:1-999-123-4567@voip-provider.example.net>
irb(main):003:0> template = Addressable::Template.new( "sip:{stuff}" )
=> #<Addressable::Template:0x3fc6b4cd796c PATTERN:sip:{stuff}>
irb(main):004:0> template.extract( "sip:1-999-123-4567@voip-provider.example.net" )
=> nil
irb(main):005:0> template = Addressable::Template.new( "sip://{stuff}" )
=> #<Addressable::Template:0x3fc6b4ce7f88 PATTERN:sip://{stuff}>
irb(main):006:0> template.extract( "sip://1-999-123-4567@voip-provider.example.net" )
=> nil
irb(main):007:0> template = Addressable::Template.new( "sip{stuff}" )
=> #<Addressable::Template:0x3fc6b4cf2514 PATTERN:sip{stuff}>
irb(main):008:0> template.extract( "sip:1-999-123-4567@voip-provider.example.net" )
=> nil
irb(main):009:0> template = Addressable::Template.new( "http:{stuff}" )
=> #<Addressable::Template:0x3fc6b4d02c70 PATTERN:http:{stuff}>
irb(main):010:0> template.extract( "http:1-999-123-4567@voip-provider.example.net" )
=> nil
irb(main):011:0> template = Addressable::Template.new( "http://{stuff}" )
=> #<Addressable::Template:0x3fc6b4d13138 PATTERN:http://{stuff}>
irb(main):012:0> template.extract( "http://1-999-123-4567@voip-provider.example.net" )
=> nil
irb(main):013:0> template.extract( "http://voip-provider.example.net" )
=> {"stuff"=>"voip-provider.example.net"}
irb(main):014:0> template = Addressable::Template.new( "http:{stuff}" )
=> #<Addressable::Template:0x3fc6b4d2a428 PATTERN:http:{stuff}>
irb(main):015:0> template.extract( "http://voip-provider.example.net" )
=> nil
```

Let me look into this further.

**Comment by pkyzivat** [comment]
Thanks! But I remain confused on how this is *supposed* to work. If {stuff} can match everything, then how are templates with more than one expression parsed? It would require arbitrary look ahead in the parser.

Note that sip URIs can contain very complex content in the user part. And they can also contain parameters using the "query" syntax, and the number and form of those can be unpredictable. Also, URI parameters using ";name=value" syntax also may follow the domain name.

**Comment by anewton1998** [comment]
So I tried two different Ruby implementations and they both have the same problem. After further investigation, it looks like an `extract` feature is not universally implemented in URI template libraries.

And with some thought, this makes sense. There can be some pretty rough cases.

Take for instance `http://example.com/{foo}{bar}`

That is a legal URI template and would expand with no problem. But how would it know what to do with this URI: `http://example.com/fudgebaz`. Which part of `fudgebaz` goes with `foo` and which part with `baz`?

I need to discuss with spec authors taking this feature out and simply replacing it with scheme narrowing, such as `uri..sip` for only SIP URIs. That's easy to do, and is what you want.

**Comment by codalogic** [comment]
Merging ideas from above, what if the part after the .. was a regular expression that had to match the scheme part of the URL only (possibly implicitly anchored to beginning and end)?  So it could look like:

    uri../sips?|https?/

That way you can specify schemes without getting sucked into trying to capture a likely ABNF description of a URI in an RE!  (Not only is it difficult to do, it seems like the wrong place to do it.)

**Comment by anewton1998** [comment]
We could simplify that further, and just have a pipe separated list of allowable schemes:

```
uri..http|https|ftp
```

And since URNs are used a lot as identifiers in protocols, we could even say that if it is a urn, the namespace identifier could be used:

```
uri..urn:ietf
```

**Comment by anewton1998** [comment]
Now that I think about it, I don't like that last part about URNs. :)

**Comment by codalogic** [comment]
The problem with `uri..http|https|ftp` is that we might have a `type-choice` of `: (uri..http|integer)`, which makes it ambiguous.

My thinking on the RE usage was that we already have ABNF and code for parsing them. While they're potentially 'heavy' for what we need, it'll be simpler to re-use them than create out own scheme, perhaps with a couple of gotchas.

**Comment by codalogic** [comment]
If we really don't want the REs, we could do:

    uri..(sip)
    uri..(http|https|ftp)

and I guess we could also support `uri..sip` if the single scheme option above looks too ugly.

**Comment by pkyzivat** [comment]
ISTM this discussion belongs on discuss@json-content-rules.org, so I'm moving over there.

**Comment by anewton1998** [comment]
this has been resolved
