### ISSUE TITLE
More newbie issues

### ISSUE THREAD

**Issue by pkyzivat** [arineng/jcrvalidator#76]
As long as I am here, I'll note other newbie concerns:

* Installation problems:

I followed the instructions to install using gem install. (Note I have no experience with Ruby.)
That went fine, but when I tried to run it I got errors that turned out to be a missing dependency (parslet). I installed that, and then ran into a couple of other dependencies before it finally ran.

* Diagnostics:

The error messages aren't very user friendly! 

I was able to verify the install by running some of the examples. But when I tried to validate the schema and matching json that I had already written I got an immense error message. I couldn't even tell whether it was the schema or the json file that was wrong. I had to step back and incrementally build up my schema and test json line by line, checking each time in order to find the errors. Eventually I earned to distinguish an error with the schema from an error with the json file, but for the most part the messages weren't very helpful beyond that.

Perhaps I just need to have my expectations properly set. I gather that there has as yet been any focus on end user diagnostics - that what I'm getting are developer debug output. That is ok for early adopters who know what they are getting into. But it isn't really enough for JCR to be used widely.

Some text in the readme about this would be helpful.

IMO it would be ideal if this ended up with a status something like xml2rfc, downloadable for those who want to, but with a web page where you can invoke it it directly and get error messages that point you in the direction of what needs to be fixed. (And yes, I do appreciate that emitting *helpful* error messages from a parser is hard.)

**Comment by anewton1998** [comment]
So the first issue is because the gemspec file doesn't list everything it needs. I'll fix that as soon as possible (on travel this week, so it may take some time).

As for the second issue, can you send email to discuss@json-content-rules.org so the other spec authors can see the request? That would be helpful.

**Comment by anewton1998** [comment]
New gems 0.5.3 (current draft syntax) and 0.6.0 (upcoming -07 draft syntax) are published with dependencies. should fix this problem.

**Comment by anewton1998** [comment]
this has been resolved.
