### ISSUE TITLE
allow specification of arrays checking for containment

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcrvalidator#8]
Currently, array rules assume arrays are compared in order.

What about a syntax to specify an array rule that merely checks that the array contains elements matching rules. There would be two types, exclusive and non-exclusive.

Given this array
    [ 1, 2, 3 ]

This is a normal rule that matches it
    [ :1, :2, :3 ]

Contains non-exclusive would be
    [# :1, :3, :integer ]

And exclusive would be
    [= :1, :3, :2 ]

The difference between exclusive and non-exclusive is that rules in non-exclusive array rules may match the same elements where as in exclusive the rules must match one and only one element.

**Comment by anewton1998** [comment]
BTW, I'm not stuck on terminology here. Perhaps we should call these sorted and unsorted rules. So there would be sorted rules (the default with no extra syntax), unsorted exclusive (using equals sign syntax), and unsorted non-exclusive (using the hash sign '#').

**Comment by anewton1998** [comment]
Also, I see these as compatible with issue #9 for pedantic arrays.

So...
    [ i1, i2 ] ; pedantic, sorted array
    [= i1, i2 ] ; pedantic, exclusively unsorted array
    [# i1, i2 ] ; pedantic, non-exclusively unsorted array
    [~ i1, i2 ] ; pedantic, sorted array
    [~= i1, i2 ] ; pedantic, exclusively unsorted array
    [~# i1, i2 ] ; pedantic, non-exclusively unsorted array
    [$ i1, i2 ] ; non-pedantic, sorted array
    [$= i1, i2 ] ; non-pedantic, exclusively unsorted array
    [$# i1, i2 ] ; non-pedantic, non-exclusively unsorted array

**Comment by anewton1998** [comment]
The terminology really should be "unordered" not "unsorted". Also, I'm leaning toward throwing out non-exclusive matching after thinking about how this could apply to objects as well as arrays. I'm thinking all matching is exclusive, that is one rule can only match one item of an array or one member of an object, and the rules are evaluated in the order in which they appear.

**Comment by codalogic** [comment]
So have you settled on only the sorted forms?  I think that's reasonable for arrays until someone comes up with a good use-case to do otherwise.

**Comment by anewton1998** [comment]
Actually, I'm thinking of arrays being matched as an ordered list or an un-ordered list. But that when matching, a sub rule in the array can match one and only one item, and that sub rules are evaluated in the order in which they are given.

So given the array rule [ :integer, :string ], it would match [ 1, "foo" ]. 

However, using the syntax in #9 , the array rule [ <unordered> :string, :integer ] would also match.

Exclusivity rule matching means that for [ 0* /a.*/, :string ] and the array [ "a1", "a2", "a3" ] that :string cannot match any of the items matched by /a.*/
This seems obvious until you start doing [ <unordered> 0* /a.*/, :string, :integer ] against something like [ "a1", 777, "a2" ]

I know that unordered matching seems to be adding complexity, but I thought of this while trying to figure out how to apply JCR to jCard. jCard is defined as an array of arrays, where in certain cases the top array must contain a sub-array containing certain content, and where that sub-array appears is not specified.

Also, I have thought about using JCR for integration tests with RDAP, where we have arrays of strings to indicate status. The order of the strings in the array is not specified, so to use JCR in a test it would need unordered matching.

**Comment by codalogic** [comment]
Ah, I think I've got it.  The unordered case is like Relax NG's Interleave pattern: http://relaxng.org/tutorial-20011203.html#IDAN1YR (and essentially what object members do anyway - but there there's no ambiguity between :/a.*/ and :string).

I agree it's a useful pattern.  I can see a way though the complexities for unordered arrays of value types, but what happens when the array's children include arrays and / or objects?

**Comment by anewton1998** [comment]
While it may be a little hard to thing about, the outcome for arrays and objects is the same for values.

So [ @(unordered) [ "fn", "", [] ], 0* [ :string, ( :"" | [ 0* :string ] ), [ 0* :string ] ] ]

Would say that the array must contain sub-arrays that conform to having a string, either an empty string or array of strings, and an array of strings, and that the sub-array that has the first item of "fn" must look a certain way.

Where did I get this contorted example? jCard!

**Comment by codalogic** [comment]
So it's definitely necessary to look into a child array / object and deduce what it matches. That's evil :-(

**Comment by anewton1998** [comment]
If you take a look at the rule evaluation code, it wasn't that hard to do. At least here. Other processing algorithms may be trickier.

**Comment by anewton1998** [comment]
this is now covered under the conversation regarding per-rule directives
