### ISSUE TITLE
Gotcha in new jcr_version_d rule

### ISSUE THREAD

**Issue by codalogic** [arineng/jcrvalidator#80]
With the current ABNF, I think we have a problem if we have a jcr-version directive followed by a number of basic type root rules. e.g.:

    #jcr-version 0.6
    integer
    string

The `integer` and `string` root types will be assumed to be part of jcr-version directive.

We can either say this is nothing to worry about as it's a bit of a corner case.  Or we can introduce a `DSP` type (for `directive space`) that doesn't allow `\n` in one-line directive mode, but does in multi-line directive mode.  We'd probably only be able to represent that as a comment.

**Comment by codalogic** [comment]
Or we could put the extensions in brackets (or something similar):

    #jcr-version 0.6 (co-constraints-1.0 doc-1.2)
    integer
    string

**Comment by codalogic** [comment]
Actually, with the `(` at the start of `(co-constraints-1.0 doc-1.2)` we'd probably like the parser to start looking for a group :-(.  Back to the `DSP` option at the moment.

**Comment by anewton1998** [comment]
EOL is in the one line directive, so I don't think this is a problem. I tested this with jcrvalidator and it works.

**Comment by codalogic** [comment]
If I put the following into my tree printer:

    #jcr-version 0.6
    # ruleset-id my_awesome_rules
    integer
    string

I get:

    [{:directive=>
       {:jcr_version_d=>{:major_version=>"0"@17, :minor_version=>"6"@19}}},
     {:directive=>{:ruleset_id_d=>{:ruleset_id=>"my_awesome_rules"@38}}},
     {:primitive_rule=>{:integer_v=>"integer"@59}},
     {:primitive_rule=>{:string=>"string"@71}}]

which is good.

Whereas, if I put in:

    #jcr-version 0.6
    integer
    string

I lose the integer root items and get:

    [{:directive=>
       {:jcr_version_d=>{:major_version=>"0"@17, :minor_version=>"6"@19}}}]

which misses the integer etc.

The following rspec test will demonstrate it:

      it 'should parse jcr-version directive major and minor numbers followed by integer root rule' do
        ex5a = <<EX5a
    # jcr-version 4.0
    integer
    string
    EX5a
        tree = JCR.parse( ex5a )
        expect(tree[0][:directive][:jcr_version_d][:major_version]).to eq("4")
        expect(tree[0][:directive][:jcr_version_d][:minor_version]).to eq("0")
        expect(tree[1][:primitive_rule][:integer_v]).to eq("integer")
        expect(tree[2][:primitive_rule][:string]).to eq("string")
      end

which I've added to https://github.com/codalogic/jcrvalidator/tree/jcr-version-gotcha

**Comment by anewton1998** [comment]
This is now fixed. The issue was the `spaces` rules that would eat `\r\n`. I created a `non_eol_spaces` rule.

**Comment by anewton1998** [comment]
FUDGE! That doesn't work for multi-line. Back to the drawing board. I think perens are the way to go.

**Comment by anewton1998** [comment]
The syntax has been changed to have extension ids inside parenthesis characters.

**Comment by codalogic** [comment]
I'm not too sure how much sleep we should lose over this, but...

...entering pedantic mode, with parenthesis it's now ambiguous whether it's the start of a group.

My solution in my C++ code was to introduce a `DSPs` ABNF rule like:

    DSPs =     ; Directive spaces
           1*WSP /     ; When in one-line directive
           sp-cmt      ; When in muti-line directive

Then use it as:

    jcr_version_d = jcr-version-kw DSPs major_version "." minor_version
        #!                 [ DSPs extension_id *( DSPs extension_id)  ]

(Side note - I've used `sp-cmt` rather than just `spaces` in DSPs.  This allows comments in directives like:

    #{ jcr-version 4.0 ; May upgrade later
           foo_1 bar_4 }

That seems worth changing whatever we do.)

If we're not happy with the context sensitive `DSPs` rule, I think we could safely support the following syntax with ambiguity:

    # jcr-version 1.0 + co-constraints-1.2 + jcr-doc-1.0

Once we've decided which route to take, I'm happy to update the ruby code and ABNF accordingly.

**Comment by anewton1998** [comment]
Well this small feature has blown up on me, huh?

I like the comments and I like the plus syntax even more than the parens. I welcome your help with the Ruby code and ABNF since I've made a complete hash of things so far.

**Comment by codalogic** [comment]
Pull request submitted.

It's good that it's highlighted something that could have caused us grief in the future.

But hopefully we're all out of good ideas for the time being :-)

**Comment by anewton1998** [comment]
this seems to have been resolved
