### ISSUE TITLE
remove pedantic directive and allow syntax for pedantic object rules

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcrvalidator#9]
Instead of a pedantic directive, allow an object rule to be specified as
    {! mrule1, mrule2 }

**Comment by anewton1998** [comment]
It occurs to me that when I coded the array rule evaluation, I just assumed that no extra elements were allowed past the ones specified by the rules. This could be made more specific by applying the pedantic syntax to arrays as well.
    [! rule1, rule2 ]

So given this array
    [ 1, 2, 3 ]

This rule would not match
    [! :1, :2 ]

But this rule would
    [ :1, :2 ]

**Comment by anewton1998** [comment]
In thinking about this some more, there are likely different default modes of dealing arrays and objects in JSON. The default for objects (or hashes) is to pull values out by the key, and anything unknown is simply ignored because it is never processed. Hence pedantic mode for a JSON object is not the norm.

But for arrays it is different. The likely different processing model for arrays is to iterate over them, thus everything in the array is processed. Anything "extra" in them must be purposefully ignored, so pedantic mode is the norm for JSON arrays.

Therefore, in JCR the default for object rule specifications should be non-pedantic and the default for array rules should be pedantic. For completeness, we should allow the specification of both but arrays default to pedantic while objects (hashes) do not. Because we need two different characters for pedantic and non-pedantic, I suggest we abandon the exclamation point ("!") and use the dollar sign ("$") for pedantic and tilde ("~") for non-pedantic.

So non-pedantic object rules:
    {~ m1, m2 }
    { m1, m2 }

Pedantic object rule:
    {$ m1,m2 }

Non-pedantic array rule
    [~ i1, i2 ]

Pedantic array rules
    [$ i1, i2 ]
    [ i1, i2 ]

**Comment by anewton1998** [comment]
I'm wondering if a term other pedantic is more appropriate.

**Comment by codalogic** [comment]
A few thoughts on this one:

I would make the default for both arrays and objects non-pedantic for a couple of reasons.  First, having different defaults for different contexts can be very confusing to the novice / infrequent user.  Second, as a rule I think you close constructs to extension at your peril!  It's very easy to get bitten by that.

To allow for arrays and objects to have different 'defaults' within a given ruleset, you could modify the #pedantic directive to have "object" and / or "array" parameters, for example:

#pedantic array ; Arrays are pedantic, objects are not

#pedantic on its own would make both array and object pedantic.

My other concern is that the syntax is going the way of Perl!  Using the principle of optimise the 20% that you use 80% of the time for brevity, and optimise the 80% that you use 20% of the clarity, I'd suggest having something like:

{ @(pedantic) m1, m2 }

The attributes would allow forms such as:

{ @(directive param1 param2 "param 3") m1, m2 } etc.

**Comment by codalogic** [comment]
Java's "final" when applied to a class seems to come this the current meaning of pedantic.  XML schema uses the word in a similar context.  Having a ruleset that has #final at the top would make you think whether that's what you really want to do!  And it's quite a short word for when you want to make only particular objects or arrays final, e.g.: { @(final) m1, m2 }

**Comment by anewton1998** [comment]
I like where you have taken this. "final" is a great way of thinking about it.

I'd prefer to get rid of the #pedantic (or even #final) type directive that does not accompany a rule because it causes, in my opinion, complexity with #import because now users and implementations have to keep track of which rules where defined in which context. Having each rule state its nature is better, if you ask me.

As for syntax, I'm thinking < > are available again. So,
    { <final> m1,m2 }
    [ <final,unordered> i1, i2 ]

I'm not following your example of the params:
    { @(directive param1 param2 "param 3") m1, m2 } 
Can you explain this further?

**Comment by anewton1998** [comment]
BTW, what's the opposite of "final"? "Non-final"?

**Comment by codalogic** [comment]
With { @(directive param1 param2 "param 3") m1, m2 } I was trying to open up the syntax so the per-item directives could have their own parameters.  For example (not that I'm suggesting this at this time!), you could have something like:

{ @(import net.arin.phone as tel) tel.m1, m2 }

to set up a local namespace alias.  So, moving to your syntax, for your second example I'd propose doing it as:

[ <final> <unorder> i1, i2 ]

to make it clear that it's 2 per-item directives.

**Comment by codalogic** [comment]
I notice that this commenting system doesn't like bare angle brackets.  It's not the only one.  Is that a reason to avoid them? :-)

**Comment by anewton1998** [comment]
Yeah, that might be a very good reason to avoid them. I like the idea of per-rule directives.

**Comment by codalogic** [comment]
If there is no longer a top-level #pedantic / #final (which makes sense), then is there a need for "non-final" per-rule directive?

**Comment by anewton1998** [comment]
I would think there is a need, because people process JSON objects differently than they process JSON arrays.

**Comment by codalogic** [comment]
I think I'm misunderstanding things then.  My thinking was that if there is no #final top-level directive to set a global default, then each separate array rule or object rule that is 'final' has to explicitly say it's 'final', otherwise it's not final.  How do you see it?

**Comment by anewton1998** [comment]
I was thinking that it would be necessary to set an array to non-final or set an object to final.

However, I'm now thinking we should just throw this whole concept away. Object rules should simply ignore members that are not matched (non-final) as most people expect, and array rules should match every item in the array as most people would expect. If there is a desire to allow an array to have items for unspecified type, they can use :any.
    [
      2*2 :integer, ; the first two items are integers
      foo_obj, ; the third item is the foo object defined by the foo_obj rule
      0* :any ; anything else
    ]

I'm not in favor of object rules needing to specify /.*/ :any because that would just litter nearly every specification.

**Comment by anewton1998** [comment]
Hmm... I'm wondering if another way to solve this is to have a :none just like we have an :any. That way an object can be explicitly limited by doing something like this:
~~~
{
  "status" : [ :string ], ; array of status strings
  "counts" : [ :integer ], ; some other thing
  0* /.*/ :none ; 0 matches means nothing, any matches means fail
}
~~~

**Comment by codalogic** [comment]
My initial thought is that I like '*:any' as the opposite of 'fixed' for arrays.  I like the defaults you have for objects and arrays (non-fixed and fixed).  

'* /.*/ : none' currently seems a bit too much like line noise though!  It might be possible to simplify the pattern to '//' giving '* // :none', but still feels quirky.  At the moment I would stick with the '@(fixed)' for that  But I might grow used to the other option with a bit more time!

**Comment by codalogic** [comment]
Thinking some more, how about:

   // : reject

So if any name matches the pattern (rather than the explicitly named object members) then the instance is rejected.  There's no need to do '* // : reject' because only one matching instance is required to reject it.

It still feels a bit like a 'clever trick' for people that are in the know.  Then again, it may be handy for people that do want to reject messages with specific members (though they could do that with higher layer logic if they wanted to).

**Comment by anewton1998** [comment]
Wow... I learn something new everyday. I had never thought of just "//" for the regex. But that works.

I'm fine with :reject instead of :none

But it actually has to be 0* :reject (or ? :reject once I put ? back in) because if there are zero matches, everything passes but if there is even one match then it rejects.

There is one more use case for :reject. Let's say I am writing a unit test to verify my JSON output looks a certain way. If I want to make sure an object doesn't have a specific member, I could do this:
~~~
{
  "stuff" : integer,
  ? "thing" : reject ; if "thing" shows up, error
}
~~~

Of course, there is no version of this for arrays, unless we wanted to do something like
~~~
[ "stuff", @(reject) "thing" ]
~~~

But then, why can't we then do something similar for objects:
~~~~
{ "stuff" : integer, @(reject) "thing" :any }
~~~~

Which do you like best?

One of the values I'm now seeing in JCR is unit testing JSON output. Let's say a spec provides some JCR with this rule: `status : integer`
For a particular unit test when I know the status is to be a specific value, I could override just the status rule with: `status : 2`

**Comment by codalogic** [comment]
I agree with your point about it having to be 0* :reject.  It does make me think that you could do:

0*0 // : any

i.e. you're not allowed any instances of unknown names with any type.  Probably too cute for its own good though!

**Comment by anewton1998** [comment]
pedantic rule set id directive removed
