### ISSUE TITLE
annotations on groups in objects

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcrvalidator#95]
this seems to be syntactically illegal both from what the code does and my reading of the parser.rb comments for the ABNF.

```
{ @{not} ( "a":any ) }
```
Is this an oversight, or is there a good reason groups in objects are not allowed to have annotations?

this problem also probably exists for arrays.

**Comment by codalogic** [comment]
I'm going with oversight :-) Looks like `object-group` and `array-group` need to be changed to:

    object-group     = annotations "(" *sp-cmt [ object-items *sp-cmt ] ")"
    array-group      = annotations "(" *sp-cmt [ array-items *sp-cmt ] ")"

Hopefully that won't cause things to explode!

**Comment by anewton1998** [comment]
Ok. I'm working on a PR for this. @codalogic your review of it will be appreciated :)

**Comment by anewton1998** [comment]
PR is in. https://github.com/arineng/jcrvalidator/pull/97
@codalogic can you review it?

**Comment by codalogic** [comment]
Looks good to me.  It's a "Yes" from me.
